# Generated by Django 4.2.6 on 2023-10-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='district',
            new_name='name',
        ),
    ]
