# Generated by Django 4.2.6 on 2023-10-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_rename_branch_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='district',
        ),
    ]
