# Generated by Django 4.2.5 on 2023-10-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_alter_branch_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='wikipedia_url',
            field=models.URLField(default=78),
            preserve_default=False,
        ),
    ]
